/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.ufg.inf.manutencao.view;

import javax.swing.JTextField;
import main.java.ufg.inf.manutencao.controller.ControllerCarregarRadoc;

/**
 *
 * @author Leonardo
 */
public class ViewCarregarRadoc extends javax.swing.JFrame {
    
    public ControllerCarregarRadoc controllerCarregarRadoc;

    /**
     * Creates new form ViewCarregarRadoc
     */
    public ViewCarregarRadoc() {
        initComponents();
        controllerCarregarRadoc = new ControllerCarregarRadoc(this);
    }
    
    public ControllerCarregarRadoc getControllerCarregarRadoc() {
        return controllerCarregarRadoc;
    }
    
     public JTextField getJTextFieldCaminhoArquivo() {
        return jTextFieldCaminhoArquivo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelLocalRadoc = new javax.swing.JLabel();
        jTextFieldCaminhoArquivo = new javax.swing.JTextField();
        jButtonEditarArquivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setText("Leitura de Arquivo Radoc");

        jLabelLocalRadoc.setText("Local Do Arquivo:");

        jTextFieldCaminhoArquivo.setEditable(false);

        jButtonEditarArquivo.setText("Editar Arquivo");
        jButtonEditarArquivo.setToolTipText("Editar diretório de envio");

        jButtonEditarArquivo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonEditarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarArquivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelLocalRadoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCaminhoArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditarArquivo))
                    .addComponent(jLabelTitulo))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLocalRadoc)
                    .addComponent(jTextFieldCaminhoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditarArquivo))
                .addContainerGap(254, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarArquivoActionPerformed
         getControllerCarregarRadoc().alterarArquivoSelecionado(getJTextFieldCaminhoArquivo());
    }//GEN-LAST:event_jButtonEditarArquivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCarregarRadoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCarregarRadoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCarregarRadoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCarregarRadoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCarregarRadoc().setVisible(true);
            }
        });
    }
    
       private void jButtonEditArquivoSelecionado(java.awt.event.ActionEvent evt) {                                                    
        getControllerCarregarRadoc().alterarArquivoSelecionado(getJTextFieldCaminhoArquivo());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarArquivo;
    private javax.swing.JLabel jLabelLocalRadoc;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldCaminhoArquivo;
    // End of variables declaration//GEN-END:variables
}
